### ISSUE TITLE
[BUG]: Can't use PSQL database as an option because of hardcoded mysql db test

### ISSUE THREAD

**Issue by jackrh** [keephq/helm-charts#10]
### Description of the bug

While you can override the connection string and Keep will now succesfully create and use a PSQL DB it will never connect on the backend unless you override or remove the init container check for mysql. 

This line here has a hard coded value for DB name and port (mysql)
[command: ['sh', '-c', 'until nc -z keep-database 3306; do sleep 1; done;']](https://github.com/keephq/helm-charts/blob/8ee82d461986d7fbcec53385a0843468d33a6334/charts/keep/templates/keep-backend.yaml#L73C8-L73C85)

### Steps To Reproduce

1. Configure keep-backend to use PSQL DB Connection string
2. Observe keep-backend init container hangs trying to connect to non existent mysql database.

**Comment by jack-hyde-wk** [comment]
That worked, thanks!

**Comment by shahargl** [comment]
https://github.com/keephq/helm-charts/pull/14
