### ISSUE TITLE
[BUG]: Can't connect Prometheus provider on k8s/Kind

### ISSUE THREAD

**Issue by guymeron** [keephq/helm-charts#17]
### Description of the bug

Unable to add Prometheus provider.
Error: An error occurred while fetching the data.

### Steps To Reproduce

Setup Kind docker 
`kind create cluster  --name=keep-kind`
Install kube-state-metrics Helm Chart
`helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`
`helm repo update`
`helm install monitoring prometheus-community/kube-state-metrics`
Install Keep Helm Chart
`helm repo add keephq https://keephq.github.io/helm-charts`
helm pull keephq/keep
`helm install keep keephq/keep`
Port forward frontend
`k port-forward svc/keep-frontend 3000`
Try to setup Prometheus provider
From http://localhost:3000/providers select Prometheus

**Comment by talboren** [comment]
Hey @guymeron :) Thank you for this issue!
Can you provide some additional context? Do you have a screenshot from the UI? Can you maybe include the logs from `keep-backend`?

**Comment by guymeron** [comment]
<img width="1728" alt="image" src="https://github.com/keephq/helm-charts/assets/1658457/48b56f7c-3a2a-4615-bf66-03085909fba4">

**Comment by talboren** [comment]
Thanks @guymeron!

1. I invite you to join our [Slack](https://slack.keephq.dev), it'll be easier to communicate :)
2. Can you try removing a k8s secret called `keep-webhook` from the namespace where Keep is deployed?
It's not a proper solution but I think it'll make it work for you for now.
